#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

console.log('🚀 Starting p5 documentation bundling... 📚✨');

const outputDir = 'doc';
const assetsDir = 'assets';
const typesFile = path.join(assetsDir, 'types', 'p5.d.ts');

// Ensure output directory exists
if (!fs.existsSync(outputDir)) {
  fs.mkdirSync(outputDir, { recursive: true });
}

// Helper function to clean JSDoc formatting
function cleanJsdocText(text) {
  if (!text) return '';
  
  // Split into lines, remove leading asterisks and whitespace, then rejoin
  const lines = text.split('\n');
  const cleanedLines = lines.map(line => {
    // Remove leading whitespace and asterisk
    let cleaned = line.replace(/^\s*\*\s?/, '');
    // Remove leading whitespace
    cleaned = cleaned.replace(/^\s+/, '');
    return cleaned;
  });
  
  // Join and normalize whitespace
  let result = cleanedLines.join(' ');
  // Clean up multiple spaces
  result = result.replace(/\s+/g, ' ');
  // Clean up multiple periods
  result = result.replace(/\.\s*\./g, '.');
  
  return result.trim();
}

// Helper function to wrap text to specified length
function wrapText(text, maxLength = 78) {
  if (!text || text.length <= maxLength) return text;
  
  const words = text.split(' ');
  const lines = [];
  let currentLine = '';
  
  for (const word of words) {
    if ((currentLine + ' ' + word).trim().length <= maxLength) {
      currentLine = (currentLine + ' ' + word).trim();
    } else {
      if (currentLine) lines.push(currentLine);
      currentLine = word;
    }
  }
  if (currentLine) lines.push(currentLine);
  
  return lines.join('\n');
}

// Module emojis mapping
const moduleEmojis = {
  'accessibility': '♿',
  'color': '🎨',
  'core': '⚙️',
  'data': '📊',
  'dom': '🌐',
  'events': '🖱️',
  'image': '🖼️',
  'io': '📁',
  'math': '🔢',
  'typography': '📝',
  'utilities': '🛠️',
  'webgl': '🎮'
};

// Helper function to create Vimdoc format with emojis
function createVimdocContent(moduleName, functions, p5Version, timestamp) {
  const emoji = moduleEmojis[moduleName] || '📚';
  
  // Create table of contents - simple flat list
  const tocFunctions = functions.map(func => 
    `  - ${func.name}()              |p5-${moduleName}-${func.name}|`
  ).join('\n');

  // Create function documentation with proper structure
  const functionDocs = functions.map(func => {
    // Clean description
    const cleanDesc = cleanJsdocText(func.description);
    const wrappedDesc = wrapText(cleanDesc);
    
    // Only show params section if there are params
    let paramsSection = '';
    if (func.params && func.params.length > 0) {
      const paramsList = func.params.map(p => {
        const cleanParamDesc = cleanJsdocText(p.description);
        return `    ${p.name}  ${cleanParamDesc}`;
      }).join('\n');
      paramsSection = `
#### Parameters:

${paramsList}
`;
    }
    
    // Clean return
    const cleanReturn = cleanJsdocText(func.returns);
    
    return `
\`${func.name}()\`                                            |p5-${moduleName}-${func.name}|

${wrappedDesc}
${paramsSection}
#### Returns:

    ${cleanReturn}

📂 *Sub-module: ${func.subModule || 'main'}*

---
`;
  }).join('\n');

  return `*p5-${moduleName}*                                         p5.js ${moduleName} docs

==============================================================================
Table of Contents                           *p5-${moduleName}-table-of-contents*

1. Functions                                                |p5-${moduleName}-functions|
${tocFunctions}

${emoji} ${moduleName.charAt(0).toUpperCase() + moduleName.slice(1)} module for p5.js

📦 p5.js Version: ${p5Version}~
⏰ Last Updated: ${timestamp}~

==============================================================================
2. Functions                                                |p5-${moduleName}-functions|

${functionDocs}
==============================================================================
Generated by p5.nvim documentation generator <https://github.com/prjctimg/p5.nvim>

vim:tw=78:ts=8:ft=help:norl:
`;
}

function extractDocumentation() {
  console.log('📖 Reading TypeScript definitions...');
  
  if (!fs.existsSync(typesFile)) {
    console.error('❌ TypeScript definitions file not found:', typesFile);
    process.exit(1);
  }
  
  const content = fs.readFileSync(typesFile, 'utf8');
  
  // Get p5 version and timestamp
  const p5Version = '1.7.7';
  const timestamp = new Date().toISOString().replace('T', ' ').replace(/\.\d+/, '');
  
  // Extract module sections and their functions
  const modules = {};
  
  // Find all inlined file references
  const moduleRegex = /\/\/ Inlined from: \.\/src\/([^\/]+)\/([^\/]+)\.d\.ts\s*\n([\s\S]*?)(?=\n\/\/ Inlined from:|$)/g;
  
  let match;
  while ((match = moduleRegex.exec(content)) !== null) {
    const [, mainCategory, subCategory, moduleContent] = match;
    
    // Extract function documentation - improved regex to handle multi-line JSDoc
    const functionDocs = [];
    
    // Match JSDoc comments with their function declarations
    // This regex handles the actual format: /** ... */ followed by function name
    const funcRegex = /\/\*\*([\s\S]*?)\*\/\s*\n\s*(?:export\s+)?function\s+(\w+)\s*\([^)]*\)\s*[:;]/g;
    
    let funcMatch;
    while ((funcMatch = funcRegex.exec(moduleContent)) !== null) {
      const [, jsdocContent, functionName] = funcMatch;
      
      // Extract description - everything before @param or @return
      let description = '';
      const descMatch = jsdocContent.match(/@param|@return/);
      if (descMatch) {
        const descEndIndex = jsdocContent.indexOf(descMatch[0]);
        description = jsdocContent.substring(0, descEndIndex).trim();
      } else {
        description = jsdocContent.trim();
      }
      
// Clean the description
      description = cleanJsdocText(description);
      
      // Extract all params - improved regex to handle multi-line descriptions
      const params = [];
      const paramRegex = /@param\s+(\w+)\s+(.+?)(?=\n\s*\*\s*@param|\n\s*\*\s*@return|\n\s*\*\/)/gs;
      let paramMatch;
      while ((paramMatch = paramRegex.exec(jsdocContent)) !== null) {
        // Clean the description (remove newlines and extra asterisks)
        let paramDesc = paramMatch[2].replace(/\n\s+\*/g, ' ').trim();
        params.push({
          name: paramMatch[1],
          description: cleanJsdocText(paramDesc)
        });
      }
      
      // Extract return value
      let returns = 'void';
      const returnMatch = jsdocContent.match(/@return\s+(.+?)(?=\n\s*\*\s*@|\n\s*\*\/)/);
      if (returnMatch) {
        returns = cleanJsdocText(returnMatch[1]);
      }
      
      functionDocs.push({
        name: functionName,
        description: description,
        params: params,
        returns: returns,
        subModule: subCategory
      });
    }
    
    // Also match method declarations (not just exported functions)
    const methodRegex = /\/\*\*([\s\S]*?)\*\/\s*\n\s*(?:export\s+)?(\w+)\s*\([^)]*\)\s*[:;]/g;
    
    let methodMatch;
    while ((methodMatch = methodRegex.exec(moduleContent)) !== null) {
      // Skip if already captured as function
      const [, jsdocContent, methodName] = methodMatch;
      if (functionDocs.some(f => f.name === methodName)) continue;
      
      // Extract description
      let description = '';
      const descMatch = jsdocContent.match(/@param|@return/);
      if (descMatch) {
        const descEndIndex = jsdocContent.indexOf(descMatch[0]);
        description = jsdocContent.substring(0, descEndIndex).trim();
      } else {
        description = jsdocContent.trim();
      }
      
      // Clean the description
      description = cleanJsdocText(description);
      
      // Extract all params - improved regex to handle multi-line descriptions
      const params = [];
      const methodParamRegex = /@param\s+(\w+)\s+(.+?)(?=\n\s*\*\s*@param|\n\s*\*\s*@return|\n\s*\*\/)/gs;
      let paramMatch;
      while ((paramMatch = methodParamRegex.exec(jsdocContent)) !== null) {
        // Clean the description (remove newlines and extra asterisks)
        let paramDesc = paramMatch[2].replace(/\n\s+\*/g, ' ').trim();
        params.push({
          name: paramMatch[1],
          description: cleanJsdocText(paramDesc)
        });
      }
      
      // Extract return value
      let returns = 'void';
      const returnMatch = jsdocContent.match(/@return\s+(.+?)(?=\n\s*\*\s*@|\n\s*\*\/)/);
      if (returnMatch) {
        returns = cleanJsdocText(returnMatch[1]);
      }
      
      functionDocs.push({
        name: methodName,
        description: description,
        params: params,
        returns: returns,
        subModule: subCategory
      });
    }
    
    // Group by main category (e.g., color, core, accessibility)
    if (functionDocs.length > 0) {
      if (!modules[mainCategory]) {
        modules[mainCategory] = [];
      }
      modules[mainCategory].push(...functionDocs);
    }
  }
  
  // Generate Vimdoc files per module
  console.log('📝 Generating Vimdoc files per module...');
  
  // Generate individual module files (one per main category)
  Object.entries(modules).forEach(([moduleName, functions]) => {
    const vimdocContent = createVimdocContent(moduleName, functions, p5Version, timestamp);
    fs.writeFileSync(path.join(outputDir, `p5-${moduleName}.txt`), vimdocContent);
  });
  
  // Generate main index file
  const indexContent = `*p5-modules*                                         p5.js modules index

==============================================================================
Table of Contents                                  *p5-modules-table-of-contents*

1. Available Modules                                      |p5-modules-available|

📚 p5.js Modules Documentation

📦 p5.js Version: ${p5Version}~
⏰ Last Updated: ${timestamp}~

==============================================================================
1. Available Modules                                      |p5-modules-available|

${Object.entries(modules).map(([moduleName, functions]) => {
  const emoji = moduleEmojis[moduleName] || '📚';
  return `- ${emoji} p5.${moduleName} - ${functions.length} functions`;
}).join('\n')}

Total: ${Object.values(modules).reduce((total, funcs) => total + funcs.length, 0)} functions across ${Object.keys(modules).length} modules

==============================================================================
Generated by p5.nvim documentation generator <https://github.com/prjctimg/p5.nvim>

vim:tw=78:ts=8:ft=help:norl:
`;

  fs.writeFileSync(path.join(outputDir, 'p5-modules.txt'), indexContent);
  
  console.log(`✅ Generated ${Object.keys(modules).length} Vimdoc module files`);
  console.log(`📊 Total functions documented: ${Object.values(modules).reduce((total, funcs) => total + funcs.length, 0)}`);
}

try {
  extractDocumentation();
  console.log('🎉 Vimdoc documentation bundling complete! 📚🎉');
} catch (error) {
  console.error('❌ Error bundling documentation:', error.message);
  process.exit(1);
}